version: '3.5'

services:
  mariadb:
    image: mariadb:10.5  # Usando a imagem do MariaDB
    container_name: zabbix-mariadb
    environment:
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: "@#8520@#"
      MYSQL_ROOT_PASSWORD: "@#8520@#"
    volumes:
      - mariadb_data:/var/lib/mysql  # Volume externo para MariaDB
       # Before create the volume, ensure the directory exists and has the correct permissions : Docker volume create --name mariadb_data 
    restart: unless-stopped
    networks:
      - zabbix-network

  zabbix-server:
    image: zabbix/zabbix-server-mysql:latest
    container_name: zabbix-server
    environment:
      DB_SERVER_HOST: mariadb  # Alterado para 'mariadb'
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: "@#8520@#"
      ZBX_WEBDRIVERURL: browser:4444
      TZ: America/Toronto
      ZBX_STARTVMWARECOLLECTORS: 3  
    volumes:
      - /data/docker/zabbix:/var/lib/zabbix  # Volume externo para Zabbix
    depends_on:
      - mariadb
    ports:
      - "10051:10051"
    restart: unless-stopped
    networks:
      - zabbix-network

  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql:latest
    container_name: zabbix-web
    environment:
      DB_SERVER_HOST: mariadb
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: "@#8520@#"
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: America/Toronto
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - zabbix-network

  zabbix-agent:
    image: zabbix/zabbix-agent:latest
    container_name: zabbix-agent
    environment:
      ZBX_SERVER_HOST: zabbix-server
    depends_on:
      - zabbix-server
    ports:
      - "10050:10050"
    restart: unless-stopped
    networks:
      - zabbix-network

  browser:
    image: selenium/standalone-chrome:latest
    container_name: browser
    shm_size: "2gb"
    ports:
      - "4444:4444"
      - "7900:7900"
    networks:
      - zabbix-network

networks:
  zabbix-network:
    driver: bridge

volumes:
  zabbix_server_data:
  mariadb_data:
