services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    restart: always
    hostname: "192.168.40.214"   # usar o mesmo host do external_url
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url "http://192.168.40.214"
        gitlab_rails['gitlab_shell_ssh_port'] = 2222

        # Se um dia você for usar HTTPS direto no GitLab com IP:
        # external_url "https://192.168.40.214"
        # nginx['redirect_http_to_https'] = true
        # nginx['ssl_certificate'] = "/etc/gitlab/ssl/gitlab.crt"
        # nginx['ssl_certificate_key'] = "/etc/gitlab/ssl/gitlab.key"

        # Habilitar ou não cadastro
        gitlab_rails['gitlab_signup_enabled'] = false

        # Se não quiser confirmação por e-mail (para lab, sem SMTP)
        gitlab_rails['gitlab_email_confirmation'] = false

    ports:
      - "80:80"
      - "443:443"   # pode deixar preparado pro futuro HTTPS
      - "2222:22"

    volumes:
      - /data/docker/gitlab/config:/etc/gitlab
      - /data/docker/gitlab/logs:/var/log/gitlab
      - /data/docker/gitlab/data:/var/opt/gitlab

    shm_size: "2gb"

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/-/health"]
      interval: 30s
      timeout: 10s
      retries: 5
